name: Godot Project Check

on:
  pull_request:
    branches:
      - master

jobs:
  godot-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.4.1
          headless: true

      - name: Check Godot version
        run: godot --version

      - name: Run Godot check
        run: godot --headless --check-only